import * as d from './doencas'

const doencas = [
    d.aids,
    d.anthrax,
    d.cancro_mole,
    d.candidiase,
    d.dengue,
    d.dermatite,
    d.doenca_de_lyme,
    d.ectima,
    d.eczemas,
    d.erisipela,
    d.escabiose,
    d.estrofulo,
    d.foliculites,
    d.furunculo,
    d.gonorreia,
    d.hanseniase,
    d.herpes,
    d.hpv,
    d.impetigo,
    d.larva_migrans,
    d.leishmaniose,
    d.miiase,
    d.molusco,
    d.paracoccidioidomicose,
    d.pediculoses,
    d.pediculoses_fitiriase,
    d.pitiriase_alba,
    d.pitiriase_versicolor,
    d.rubeola,
    d.rubeola_congenita,
    d.sarampo,
    d.sifilis,
    d.tinha_do_corpo,
    d.tinha_do_couro_cabeludo,
    d.tinha_dos_pes,
    d.tuberculose,
    d.tungiase,
    d.urticaria,
    d.varicela,
    d.verrugas,
]

export default doencas;
